-- Enable pgvector extension for embeddings
create extension if not exists vector;

-- Properties Table
create table properties (
  id bigint generated by default as identity primary key,
  compound_name text,
  type text, -- Apartment, Villa, etc.
  location text, -- New Cairo, etc.
  price numeric,
  beds integer,
  baths integer,
  area numeric, -- in sqm
  delivery_date text, -- e.g. "2026"
  monthly_installment numeric,
  installment_years integer,
  sale_type text, -- Developer vs Resale
  url text,
  description text, -- Full text for context
  embedding vector(1536), -- OpenAI Embedding
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Users Table
create table users (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chat Sessions Table
create table chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chat Messages Table (History)
create table chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid references chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transactions Table
create table transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id),
  property_id bigint references properties(id),
  amount numeric not null,
  status text check (status in ('pending', 'confirmed', 'failed')),
  blockchain_tx_hash text,
  stripe_payment_id text, -- or paymob
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
