-- Enable pgvector extension for embeddings
create extension if not exists vector;

-- Properties Table (mirrors backend/app/models.py Property class)
create table if not exists properties (
  id bigint generated by default as identity primary key,
  title text,
  description text,
  type text,
  location text,
  compound text,
  developer text,
  price numeric,
  price_per_sqm numeric,
  size_sqm integer,
  bedrooms integer,
  bathrooms integer,
  finishing text,
  delivery_date text,
  down_payment integer,
  installment_years integer,
  monthly_installment numeric,
  maintenance_fee_pct integer,
  delivery_payment numeric,
  image_url text,
  nawy_url text,
  sale_type text,
  is_delivered boolean default false,
  is_cash_only boolean default false,
  land_area integer,
  nawy_reference text,
  is_nawy_now boolean default false,
  scraped_at timestamp with time zone,
  embedding vector(1536),
  is_available boolean default true,
  last_scrape_run_id varchar(36),
  mirrored_image_url text,
  price_flag varchar(50),
  content_hash varchar(64),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Indexes
create index if not exists ix_properties_title on properties(title);
create index if not exists ix_properties_location on properties(location);
create index if not exists ix_properties_price on properties(price);
create index if not exists ix_properties_size_sqm on properties(size_sqm);
create index if not exists ix_properties_last_scrape_run_id on properties(last_scrape_run_id);
create unique index if not exists uq_properties_nawy_url
  on properties(nawy_url) where nawy_url is not null and nawy_url <> '';
create index if not exists ix_properties_content_hash on properties(content_hash);

-- Users Table
create table users (
  id uuid default gen_random_uuid() primary key,
  email text unique not null,
  password_hash text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chat Sessions Table
create table chat_sessions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Chat Messages Table (History)
create table chat_messages (
  id bigint generated by default as identity primary key,
  session_id uuid references chat_sessions(id) on delete cascade,
  role text not null check (role in ('user', 'assistant')),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Transactions Table
create table transactions (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references users(id),
  property_id bigint references properties(id),
  amount numeric not null,
  status text check (status in ('pending', 'confirmed', 'failed')),
  stripe_payment_id text, -- or paymob
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
