"""Marketing materials FAQ table

Revision ID: 018_marketing_materials
Revises: 017_scraper_hardening
Create Date: 2026-03-16

Creates:
- marketing_materials table
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018_marketing_materials'
down_revision = '017_scraper_hardening'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'marketing_materials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('category', sa.String(length=100), nullable=False),
        sa.Column('question_ar', sa.Text(), nullable=False),
        sa.Column('question_en', sa.Text(), nullable=False),
        sa.Column('answer_ar', sa.Text(), nullable=True),
        sa.Column('answer_en', sa.Text(), nullable=True),
        sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
        sa.Column('last_run_status', sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketing_materials_category'), 'marketing_materials', ['category'], unique=False)
    op.create_index(op.f('ix_marketing_materials_id'), 'marketing_materials', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketing_materials_id'), table_name='marketing_materials')
    op.drop_index(op.f('ix_marketing_materials_category'), table_name='marketing_materials')
    op.drop_table('marketing_materials')
    # ### end Alembic commands ###
